// https://en.wikipedia.org/wiki/DVD_region_code
typedef enum XCONFIG_DVDREGION {
	REGION_USA_CANADA_BERMUDA = 0x1,
	REGION_EU_JP = 0x2,
	REGION_KOREA = 0x3,
	REGION_AUSTRAILIA_OCEANIA = 0x4,
	REGION_AFRICA_DPRK = 0x5,
	REGION_CHINA = 0x6,
	REGION_ASIA = 0x7,
	REGION_SPACE = 0x8,
	REGION_FREE = 0xFF
} XCONFIG_DVDREGION;

typedef enum XCONFIG_CATEGORY {
	CATEGORY_UNK0 = 0,
	CATEGORY_UNK1 = 1,
	CATEGORY_DVD = 2,
} XCONFIG_CATEGORY;

typedef enum XCONFIG_ENTRY {
	ENTRY_UNK0 = 0,
	ENTRY_UNK1 = 1,
	ENTRY_UNK2 = 2,
	ENTRY_UNK3 = 3,
	ENTRY_REGION = 4,
} XCONFIG_ENTRY;